In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

df = pd.read_csv("EntriesGender.csv")
df

               Discipline  Female  Male
0          3x3 Basketball      32    32
1                 Archery      64    64
2     Artistic Gymnastics      98    98
3       Artistic Swimming     105     0
4               Athletics     969  1072
5               Badminton      86    87
6       Baseball/Softball      90   144
7              Basketball     144   144
8        Beach Volleyball      48    48
9                  Boxing     102   187
10           Canoe Slalom      41    41
11           Canoe Sprint     123   126
12  Cycling BMX Freestyle      10     9
13     Cycling BMX Racing      24    24
14  Cycling Mountain Bike      38    38
15           Cycling Road      70   131
16          Cycling Track      90    99
17                 Diving      72    71
18             Equestrian      73   125
19                Fencing     107   108
20               Football     264   344
21                   Golf      60    60
22               Handball     168   168
23                 Hockey     192   192
24                   Judo     192   201
25                 Karate      40    42
26      Marathon Swimming      25    25
27      Modern Pentathlon      36    36
28    Rhythmic Gymnastics      96     0
29                 Rowing     257   265
30           Rugby Sevens     146   151
31                Sailing     175   175
32               Shooting     178   178
33          Skateboarding      40    40
34         Sport Climbing      20    20
35                Surfing      20    20
36               Swimming     361   418
37           Table Tennis      86    86
38              Taekwondo      65    65
39                 Tennis      94    97
40  Trampoline Gymnastics      16    16
41              Triathlon      55    55
42             Volleyball     144   144
43             Water Polo     122   146
44          Weightlifting      98    99
45              Wrestling      96   193

In [2]:
Discipline = df["Discipline"]
Female = df["Female"]
Male = df["Male"]
Sum = 0
TheSum = []

for sum_1 in range(46):
    Sum = Female[sum_1]+Male[sum_1]
    TheSum.append(Sum)
    Sum = 0

In [3]:
Ar = np.array([list(Female),list(Male)])
SunFemale = Ar[0].sum()
SunMale = Ar[1].sum()

In [4]:
from tkinter import*
from tkinter import ttk
Window = Tk()
Window.title("EntriesGender")
Window.geometry("1200x720")
LB = Label(Window,text="มีนักกีฬาแต่ละประเภทกี่คน",font=("Arial Bold",20))
LB.grid(column=0,row=0)
LB1 = Label(Window,text="มีนักกีฬาหญิงทั้งหมด"+str(SunFemale)+"คน",font=("Arial Bold",20))
LB1.grid(column=1,row=1)
LB2 = Label(Window,text="มีนักกีฬาชายทั้งหมด"+str(SunMale)+"คน",font=("Arial Bold",20))
LB2.grid(column=1,row=2)

Tex = ttk.Combobox(Window,values = list(Discipline),width=20)
Tex.grid(column=0,row=2)

def BUTTON1():
    TEXT = Tex.get()
    for i in range(len(list(Discipline))):
        if str(TEXT) == str(list(Discipline)[i]):
            LB.configure(text="มีนักกีฬาประเภท"+TEXT+"เท่ากับ"+str(TheSum[i])+"คน")

BT = Button(Window,text="Click",font=("Arial Bold",20),command=BUTTON1)
BT.grid(column=0,row=1)
Window.mainloop()